# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#export PATH='/Users/vamkatra/Documents/DevSoftwares/flutter/bin':$PATH

lane :analyze do
    sh("flutter analyze")
end

lane :unit_tests do
    Dir.chdir("../src") do
        sh("flutter test --coverage")
    end
end

lane :unit_tests_coverage_report do
    Dir.chdir("../fastlane") do
        sh("bash code_coverage.sh")
    end
    
    Dir.chdir("../src") do
        sh("flutter test --coverage")
    end
end

lane :unit_tests_coverage_report_html do
    Dir.chdir("../fastlane") do
        sh("bash code_coverage.sh")
    end
    
    Dir.chdir("../src") do
        sh("flutter test --coverage")
        sh("brew install lcov")
        
        sh("genhtml coverage/lcov.info -o coverage/html")
    end
    
    sh("bash minimum_code_coverage.sh 2.1")
end

lane :build_android do
    #Dir.chdir("../android") do
        sh("flutter build apk")
    #end
end

lane :build_android_and_upload do |options|
    #Dir.chdir("../android") do
    #    sh("flutter build apk")
    #end
        
    #Dir.chdir("../") do
    
        #sh("ls")
        
        appcenter_upload(
            api_token: options[:appcenter_key],
            owner_name: "vp",
            owner_type: "organization", # Default is user - set to organization for appcenter organizations
            app_name: "neomobileapp-android",
            file: "build/app/outputs/apk/release/app-release.apk",
            #notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
            #release_notes: options[:branchName]
        )
    #end
end

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    fastlane code_coverage
  end
  
  lane :build_iOS do
    
  end
end


platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
