#include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  
  errors:
    unused_field: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    use_key_in_widget_constructors: error
    sized_box_for_whitespace: error
    prefer_is_empty: error
    sort_child_properties_last: error
    unused_element: error
    unused_local_variable: error
    avoid_print: error
    dead_code: error
    dead_null_aware_expression: error
    unused_import: error
    unnecessary_import: error
    duplicate_import: error
    empty_catches: error
        

  exclude:
    - "**/*.g.dart"
    - "lib/**/*.g.dart"


linter:

  rules:
    unnecessary_string_escapes: false
    depend_on_referenced_packages: false
    constant_identifier_names: false
    unnecessary_overrides: false
    omit_local_variable_types: false
    non_constant_identifier_names: false
    always_declare_return_types: true    