name: shared_dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

dependencies:
  flutter:
    sdk: flutter
  # firebase_dynamic_links: ^5.4.8
  # firebase_core: ^2.24.2
  shimmer: ^3.0.0
  flutter_html:
  
  task_manager:
    path: ../../../common/task_manager/app-mobile-taskmanager/src/

  core:
    path: ../../../common/core/app-mobile-core/src/

  network_manager:
    path: ../../../common/network_manager/app-mobile-networkmanager/src/

  widget_library:
    path: ../../../common/widgets/app-mobile-widgets/src/

  # NFC
  flutter_nfc_kit: ^3.4.2
  ndef: ^0.3.3
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mockito: ^5.4.4
  uuid: ^4.3.2
  