include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - build/**
    - test/**.mocks.dart
  strong-mode:
    implicit-casts: false


linter:

  rules:
    unnecessary_string_escapes: false
    depend_on_referenced_packages: false
    constant_identifier_names: false
    unnecessary_overrides: false
    omit_local_variable_types: false
    non_constant_identifier_names: false
    always_declare_return_types: true
