include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false


linter:

  rules:
    unnecessary_string_escapes: false
    depend_on_referenced_packages: false
    constant_identifier_names: false
    unnecessary_overrides: false
    omit_local_variable_types: false
    non_constant_identifier_names: false
    always_declare_return_types: true
        
  # rules:
  #   - camel_case_types
  #   - close_sinks
  #   # - lines_longer_than_80_chars

