targets:
  $default:
    sources:
        - $package$
        - "lib/**"
        - "test/**"
    builders:
      json_serializable|json_serializable:
        generate_for:
            - "lib/**/**access_scope.dart"
      mockito|mockBuilder:
        generate_for:
          - "test/**.dart"

          
            