{
  "dependencies" => {"json_annotation" => "^4.5.0"},
  "dev_dependencies" => {
    "build_runner" => "^2.1.1",
    "json_serializable" => "^6.2.0",
    "freezed" =>"",
    "golden_toolkit" => "^0.13.0",
    "import_sorter" => "^4.6.0",
    "flutter_lints" => "^1.0.4",
    "mockito" => "^5.1.0",
    "pedantic" => "^1.11.0",
  }
}