name: main_app
description: "It's for booking demo app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


flutter:
  uses-material-design: true

  assets:
    - assets/styles/
    - assets/lang/
    - assets/configuration/
    - assets/network-mocks/
    - assets/environment/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/video/

dependencies:
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  flutter:
    sdk: flutter
  flutter_html:
  package_info_plus: ^8.0.0
  connectivity_plus: ^5.0.2
  carousel_slider: ^4.2.1
  step_progress_indicator: ^1.0.2
  file_picker: ^6.1.1
  extended_image: ^8.2.0
  permission_handler:
  url_launcher:

  mime: ^1.0.5

  webview_flutter:
  path_provider: ^2.1.1
  universal_io:
  uuid: ^4.3.2
  shared_dependencies:
    path: features/shared_dependencies/

  task_manager:
    path: ../common/task_manager/app-mobile-taskmanager/src/

  network_manager:
    path: ../common/network_manager/app-mobile-networkmanager/src/

  deeplink_manager:
    path: ../common/deeplink_manager/app_mobile_deeplinkmanager/src

  widget_library:
    path: ../common/widgets/app-mobile-widgets/src/

  core:
    path: ../common/core/app-mobile-core/src/

  presentation:
    path: features/presentation/
  domain:
    path: features/domain/
  data:
    path: features/data/
  database:
    path: ../common/database/
  download_manager:
    path: ../common/download_manager/

  # firebase_monitor:
  #   path: ../common/firebase_monitor/

  security_suit:
    path: ../common/security_suit/

  theme_font:
    path: ../common/theme_font

  youtube_player_iframe: ^5.1.2
  shimmer: ^3.0.0


dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed:
  golden_toolkit: ^0.15.0
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  analyzer: ^5.4.0

dependency_overrides:
  intl: ^0.19.0
  flick_video_player: ^0.7.0
  video_player: ^2.8.6
  win32: ^5.5.0
  visibility_detector: ^0.4.0+2