#!/bin/sh
(cd core/app-mobile-core/src && flutter clean)
(cd core/app-mobile-core/src && rm pubspec.lock)
(cd core/app-mobile-core/src/example && flutter clean)
(cd core/app-mobile-core/src/example && rm pubspec.lock)
(cd network_manager/app-mobile-networkmanager/src && flutter clean)
(cd network_manager/app-mobile-networkmanager/src && rm pubspec.lock)
# (cd network_manager/app-mobile-networkmanager/src/example && flutter clean)
# (cd network_manager/app-mobile-networkmanager/src/example && rm pubspec.lock)
(cd task_manager/app-mobile-taskmanager/src && flutter clean)
(cd task_manager/app-mobile-taskmanager/src && rm pubspec.lock)
(cd widgets/app-mobile-widgets/src && flutter clean)
(cd widgets/app-mobile-widgets/src && rm pubspec.lock)
(cd widgets/app-mobile-widgets/src/example && flutter clean)
(cd widgets/app-mobile-widgets/src/example && rm pubspec.lock)
(cd deeplink_manager/app_mobile_deeplinkmanager/src && flutter clean)
(cd deeplink_manager/app_mobile_deeplinkmanager/src && rm pubspec.lock)
(cd firebase_monitor && flutter clean)
(cd firebase_monitor && rm pubspec.lock)
(cd security_suit && flutter clean)
(cd security_suit && rm pubspec.lock)
(cd download_manager && flutter clean)
(cd download_manager && rm pubspec.lock)
(cd database && rm pubspec.lock)
(cd theme_font && rm pubspec.lock)