#!/bin/sh
(cd core/app-mobile-core/src && pwd && flutter pub get)
(cd core/app-mobile-core/src/example && pwd && flutter pub get)
(cd network_manager/app-mobile-networkmanager/src && pwd && flutter pub get)
# (cd network_manager/app-mobile-networkmanager/src/example && pwd && flutter pub get)
(cd task_manager/app-mobile-taskmanager/src && pwd && flutter pub get)
(cd widgets/app-mobile-widgets/src && pwd && flutter pub get)
(cd widgets/app-mobile-widgets/src/example && pwd && flutter pub get)
(cd deeplink_manager/app_mobile_deeplinkmanager/src && pwd && flutter pub get)
(cd firebase_monitor && pwd && flutter pub get)
(cd firebase_monitor/example && pwd && flutter pub get)
(cd security_suit && pwd && flutter pub get)
(cd download_manager && pwd && flutter pub get)
(cd database && pwd && flutter pub get)
(cd theme_font && pwd && flutter pub get)
